name: app_shoes_ec
description: "VMO"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  dotted_line: ^3.2.2
  dotted_border: ^2.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/common/appicon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/cart/
    - assets/icons/common/
    - assets/icons/flags/
    - assets/icons/mode/
    - assets/icons/shoes/
  
